# Generated by Django 2.0.2 on 2020-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='uri',
            field=models.CharField(default='https://', max_length=50),
            preserve_default=False,
        ),
    ]
