# Generated by Django 2.0.2 on 2020-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uri',
            field=models.CharField(default='home', max_length=50),
        ),
    ]
