# Generated by Django 2.0.2 on 2020-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='achievment',
            name='uri',
        ),
        migrations.AlterField(
            model_name='achievment',
            name='summary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='achievment',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
