# Generated by Django 2.0.2 on 2020-05-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0002_auto_20200527_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
